version: '3'
services: 
  airports:
    build: 
      context: ./airports
      dockerfile: Dockerfile
    image: airports
    volumes: 
      - airports:/home/simphiwe/airports
    container_name: airports
    ports: 
      - "8000:8000"
    networks:
      - network1
  
  countries:
    build: 
      context: ./countries
      dockerfile: Dockerfile
    image: countries
    volumes: 
      - countries:/home/simphiwe/countries
    container_name: countries
    ports: 
      - "8080:8080"
    networks:
      - network2

networks:
  network1:
  network2:

volumes:
  airports:
  countries: