version: '3'
services: 
  airports:
    build: 
      context: ./airports
      dockerfile: "Dockerfile"
    image: airports
    ports: 
      - "8000:8080"
    volumes: 
      - ./airports:/build
    
  
  countries:
    build: 
      context: ./countries
      dockerfile: "Dockerfile"
    image: countries
    ports: 
      - "8001:8080"
